### ISSUE TITLE
Custom CSS option

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/teammates#11]
It's better to suggest Advanced CSS Editor, no? @rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani you mean remove the Custom CSS section from the plugin?

**Comment by HardeepAsrani** [comment]
Yup, and suggested the plugin instead. @rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani and what about the users that use that section at this moment?
Also, I don't think we're gonna invest much time in this plugin for now

**Comment by HardeepAsrani** [comment]
@rodica-andronache Yea, that's true. We can close then.
