### ISSUE TITLE
New name for team plugin

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/teammates#2]

**Comment by rodica-andronache** [comment]
Are cineva vre-o idee aici?

**Comment by abaicus** [comment]
Zisese Marius G ceva de "Meet the team showcase". Asta dupa keywords... mie mi se pare putin cam keyword stuffing... voi ce parere aveti? Mai zicea si Sabina ceva de "homies" parca... :D

**Comment by rodica-andronache** [comment]
A ramas numele: Teammates
