### ISSUE TITLE
Banner and icon images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/teammates#8]

**Comment by abaicus** [comment]
![banner_teammates](https://cloud.githubusercontent.com/assets/15010186/14738440/32ffe0f4-088a-11e6-903a-c649f70bfdfc.png)
![icon_teammates](https://cloud.githubusercontent.com/assets/15010186/14738441/33059cce-088a-11e6-8a6f-b6fef13c9e5c.png)
